config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  authenticated do
    root 'posts#index', as: :authenticated
  end
  root 'static_pages#index'
  get '/users/:id/change_avatar', to: 'users#change_avatar', as: 'change_avatar'
  post "/friends/add" => "friends/add"
  post "/friends/reject" => "friends/reject"
  post "/friends/remove" => "friends/remove"
  get "/friends/search" => "friends/search"
  post "/friends/search" => "friends/search"
  get '/privacy-policy', to: 'static_pages#privacy', as: 'privacy'
  get '/terms-of-use', to: 'static_pages#terms', as: 'terms'
  resources :posts do
    resources :comments, only: :create
  end
  resources :friends, only: [:index, :create]
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :message, presence: true, length: { minimum: 1, maximum: 240 }

  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :caption, presence: true, length: { minimum: 1, maximum: 120 }
  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

  belongs_to :user
  has_many :comments

  def new_family_post_email
    NotificationMailer.welcome_email(self).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader
  has_many :posts
  has_many :comments
  has_friendship
  after_create :send_welcome_email

  def friends?
    self.friends
  end

  def friend_requests?
    self.requested_friends.any?
  end

  def requested_friends?
    self.pending_friends.any?
  end

  def invite_friend(user)
    self.friend_request(user)
  end

  def send_welcome_email
    NotificationMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize}", status: status
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @post = Post.find_by_id(params[:post_id])
    return render_not_found if @post.blank?
    @comment = @post.comments.create(comment_params.merge(user: current_user))
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @friends = @user.friends
    @requests = @user.requested_friends
    @pending = @user.pending_friends
  end

  def create
    @user = current_user
    friend = User.find_by(id: params[:id])
    @user.friend_request(friend)
    NotificationMailer.send_incoming_request_email(friend, @user)
    redirect_to friends_path
  end

  def add
    @user = current_user
    friend = User.find_by(id: params[:id])
    @user.accept_request(friend)
    NotificationMailer.send_accepted_request_email(@user, friend)
    redirect_to friends_path
  end

  def reject
    @user = current_user
    friend = User.find_by(id: params[:id])
    @user.decline_request(friend)

    redirect_to friends_path
  end

  def remove
    @user = current_user
    friend = User.find_by(id: params[:id])
    @user.remove_friend(friend)

    redirect_to friends_path
  end

  def search
    @user = current_user
    @requests = @user.requested_friends
    @pending = @user.pending_friends
    @friends = @user.friends

    if params[:search]
      @search = params[:search].downcase
      @results = User.all.select do |user|
        user_fullname = user.firstname.downcase + " " + user.lastname.downcase
        user_fullname == @search || user.email.downcase == @search
      end
    else
      redirect_to friends_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    # create array containing user and all friends
    user_and_friends = []
    user_and_friends << current_user
    current_user.friends.each do |friend|
      user_and_friends << friend
    end

    # all allowed posts for user
    @allowed_posts = Post.order(created_at: :desc).reject { |post| !user_and_friends.include?(post.user) }
  end

  def show
    @post = Post.find_by_id(params[:id])
    @comment = Comment.new

    # create array containing user and all friends
    user_and_friends = []
    user_and_friends << current_user
    current_user.friends.each do |friend|
      user_and_friends << friend
    end

    # all allowed posts for user
    allowed_posts = Post.order(created_at: :desc).reject { |post| !user_and_friends.include?(post.user) }

    @newer_post = allowed_posts.select{|post| post.id > @post.id}.last
    @older_post = allowed_posts.select{|post| post.id < @post.id}.first

    return render_not_found if @post.blank?
    return render_not_found(:forbidden) if @post.user != current_user && @post.user.friends_with?(current_user) == false
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.valid?
      NotificationMailer.send_new_family_post_email(@post)
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
    return render_not_found(:forbidden) if @post.user != current_user
  end

  def update
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
    return render_not_found(:forbidden) if @post.user != current_user
    @post.update_attributes(post_params)
    if @post.valid?
      redirect_to post_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
    return render_not_found(:forbidden) if @post.user != current_user
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:photo, :caption)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    return render_not_found if @user.blank?
    return render_not_found(:forbidden) if @user != current_user
    @user.update_attributes(user_params)
    if @user.valid?
      redirect_to user_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def change_avatar
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/index.html.erb
<div class="container py-5">
  <h2 class="mb-4">Family</h2>

  <div class="row mb-5">
    <div class="col-12 col-md-4 mb-3 section">
      <h4 class="mb-4">Incoming requests:</h4>
      <% if @user.friend_requests? %>
        <% @requests.each do |friend| %>
          <div class="family-avatar-container mb-4">
            <% if User.find(friend).avatar.present? %>
              <%= image_tag User.find(friend).avatar_url(:thumb), class: 'avatar family-avatar' %>
            <% else %>
              <%= image_tag 'default_avatar.jpg', class: 'avatar family-avatar' %>
            <% end %>
            <strong class="d-block">
              <%= "#{User.find(friend).firstname} #{User.find(friend).lastname}" %>
            </strong>
            <div class="d-flex justify-content-center">
              <div class="d-inline">
                <%= form_tag ({controller: 'friends', action: 'add', method: 'post', id: friend.id}) do %>
                  <input class="btn btn-green btn-sm mt-2 mx-1" type=submit value='Accept'>
                <% end %>
              </div>
              <div class="d-inline">
                <%= form_tag ({controller: 'friends', action: 'reject', method: 'post', id: friend.id}) do %>
                  <input class="btn btn-danger btn-sm mt-2 mx-1" type=submit value='Deny'>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>None currently</p>
      <% end %>
    </div>

    <div class="col-12 col-md-4 mb-3 section">
      <h4 class="mb-4">Pending requests:</h4>
      <% if @user.requested_friends? %>
        <% @pending.each do |friend| %>
          <div class="family-avatar-container mb-4">
            <% if User.find(friend).avatar.present? %>
              <%= image_tag User.find(friend).avatar_url(:thumb), class: 'avatar family-avatar' %>
            <% else %>
              <%= image_tag 'default_avatar.jpg', class: 'avatar family-avatar' %>
            <% end %>
            <br />
            <strong>
              <%= "#{User.find(friend).firstname} #{User.find(friend).lastname}"  %>
            </strong>
          </div>
        <% end %>
      <% else %>
        <p>None currently</p>
      <% end %>
    </div>

    <div class="col-12 col-md-4 mb-3">
      <h4 class="mb-4">Find family members:</h4>
      <%= form_tag ({controller: 'friends', action: 'search'}) do %>
        <input type="text" name="search" id="search" class="mb-1">
        <input class="btn btn-blue" type="submit" name="commit" value="Search" data-disable-with="Search">
      <% end %>
      <p class="text-muted small mt-2">Enter the first and last name or e-mail address of the family member you want to find</p>
    </div>
  </div>

  <h4 class="mb-4">Your family:</h4>

  <% if ! @user.friends.empty? %>
    <% @friends.each do |friend| %>
      <div class="d-inline-block m-3">
        <% if User.find(friend).avatar.present? %>
          <%= image_tag User.find(friend).avatar_url(:thumb), class: 'avatar family-avatar' %>
        <% else %>
          <%= image_tag 'default_avatar.jpg', class: 'avatar family-avatar' %>
        <% end %>
        <strong class="d-block">
          <%= "#{User.find(friend).firstname} #{User.find(friend).lastname}"  %>
        </strong>
        <%= form_tag ({controller: 'friends', action: 'remove', method: 'post', id: friend.id}) do %>
          <input class="btn btn-danger btn-sm mt-2" type=submit value='Remove'>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p>You have not added any family members yet.</p>
  <% end %>
</div>

app/views/friends/search.html.erb
<div class="container py-5">
  <h2 class="mb-4">Search results</h2>

  <div class="family-members mb-4">
    <% if @results == [] %>
      <p class="lead"><strong>No results found</strong></p>
      <p><strong>NOTE:</strong> Your search must match either the <u>first AND last name</u> or the <u>full e-mail address</u> of the family member you are trying to find.</p>
      <%= image_tag 'anything.gif', class: 'img-fluid' %>
    <% else %>
      <% @results.each do |user| %>
        <% if user.firstname == current_user.firstname && user.lastname == current_user.lastname || user.email == current_user.email %>
          <p class="lead"><strong>You have searched for yourself.</strong></p>
          <%= image_tag 'yourself.gif', class: 'img-fluid' %>
        <% else %>
          <div class="family-avatar-container d-inline-block m-3">
            <% if User.find(user).avatar.present? %>
              <%= image_tag User.find(user).avatar_url(:thumb), class: 'avatar family-avatar' %>
            <% else %>
              <%= image_tag 'default_avatar.jpg', class: 'avatar family-avatar' %>
            <% end %>
            <br />
            <strong>
              <%= "#{User.find(user).firstname} #{User.find(user).lastname}"  %>
            </strong>
            <% if @pending.include?(user) %>
              <p class="text-muted mt-2">You have already sent an invitation to this person and are waiting for them to Accept or Deny it.</p>
              <%= image_tag 'waiting.gif', class: 'img-fluid' %>
            <% elsif @requests.include?(user) %>
              <p class="text-muted mt-2 mb-0">You already have an incoming invitation from this person. Click below to Accept or Deny it.</p>
              <div class="d-flex justify-content-center mb-4">
                <div class="d-inline">
                  <%= form_tag ({controller: 'friends', action: 'add', method: 'post', id: user.id}) do %>
                    <input class="btn btn-green btn-sm mt-2 mx-1" type=submit value='Accept'>
                  <% end %>
                </div>
                <div class="d-inline">
                  <%= form_tag ({controller: 'friends', action: 'reject', method: 'post', id: user.id}) do %>
                    <input class="btn btn-danger btn-sm mt-2 mx-1" type=submit value='Deny'>
                  <% end %>
                </div>
              </div>
              <%= image_tag 'offer.gif', class: 'img-fluid' %>
            <% elsif @friends.include?(user) %>
              <p class="text-muted mt-2">This person has already been added to your family.</p>
              <%= image_tag 'family.gif', class: 'img-fluid' %>
            <% else %>
              <%= form_tag ({controller: 'friends', action: 'create', method: 'post', id: user.id}) do %>
                <input class="btn btn-outline-success btn-sm mt-2" type=submit value='Invite to my family'>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%= link_to 'Back to Family', friends_path, class: 'btn btn-blue' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Family Photo Feed</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body class="d-flex flex-column h-100">
    <header>
      <nav class="navbar navbar-light sticky-top navbar-expand-lg">
        <div class="container-sm">
          <%= link_to 'family', root_path, class: 'navbar-brand mr-1' %><%= link_to 'photo', root_path, class: 'navbar-brand navbar-brand-green mr-1' %><%= link_to 'feed', root_path, class: 'navbar-brand' %>

          <div class="d-none d-lg-block text-muted small">
            <% if current_user %>
              Hello, <%= current_user.firstname %>!
            <% end %>
          </div>

          <button class="navbar-toggler ml-auto custom-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar" aria-controls="collapsingNavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div id="collapsingNavbar" class="collapse navbar-collapse align-self-center">
            <ul class="navbar-nav ml-auto">
              <% if current_user %>
                <li class="nav-item ml-3">
                  <%= link_to 'Upload', new_post_path, class: 'nav-link' %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to 'Profile', user_path(current_user), class: 'nav-link' %>
                </li><li class="nav-item ml-3">
                  <%= link_to 'Family', friends_path, class: 'nav-link d-inline-block' %>
                    <% if current_user.requested_friends.count > 0 %>
                      <span class="badge badge-pill badge-danger d-inline">
                        <%= current_user.requested_friends.count %>
                      </span>
                    <% end %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </li>
              <% else %>
                <li class="nav-item ml-3">
                  <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container-fluid text-center">
      <%= yield %>
    </main>

    <footer class="footer py-3">
      <div class="container small">
        <%= link_to 'Privacy Policy', privacy_path %>
        <%= link_to 'Terms of Use', terms_path, class: 'ml-2 ml-sm-3' %>

        <span class="text-muted float-right">&copy; 2020 Family Photo Feed</span>
      </div>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %>
    <%= f.text_area :caption %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="form-reg py-5">
  <h2 class="mb-4">Edit Post</h2>

  <%= simple_form_for @post do |f| %>
    <%= f.input :photo %>
    <%= f.input :caption %>
    <%= f.submit 'Update', class: 'btn btn-green btn-300 mt-4 mb-2' %>
  <% end %>

  <%= link_to 'Cancel', post_path, class: 'btn btn-outline-blue btn-300' %>
</div>

app/views/posts/index.html.erb
<div class="mt-3 mt-sm-0 py-0 py-sm-5">
  <% @allowed_posts.each do |post| %>
    <div class="thumb-container thumb-container-size">
      <%= link_to post_path(post) do %>
        <%= image_tag post.photo_url(:thumb), class: 'thumbnail mr-4' if post.photo.present? %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="py-5">
  <%= simple_form_for @post, html: { class: "form-upload" } do |f| %>
    <h2 class="mb-4">Upload</h2>
    <%= f.input :photo, label_html: { class: 'float-left' }, input_html: { class: 'btn btn-outline-green' }  %>
    <%= f.input :caption, label_html: { class: 'float-left' }, input_html: { class: 'strong' } %>
    <div class="d-flex justify-content-center mt-4">
      <%= f.submit 'Post', class: 'btn btn-green btn-300 d-block d-justify-self-center mb-2' %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to 'Cancel', posts_path, class: 'btn btn-outline-blue btn-300 d-block' %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="row align-items-center pt-0 pb-3 py-sm-5">
  <div class="col-2 offset-4 col-sm-1 offset-sm-0 p-0 order-2 order-sm-1 mt-3">
    <% if !@newer_post.nil? %>
      <%= link_to post_path(@newer_post) do %>
        <i class="fas fa-arrow-left fa-2x d-block"></i>
        <small>Newer</small>
      <% end %>
    <% end %>
  </div>

  <div class="col-12 col-sm-10 card p-0 order-1 order-sm-2">
    <div class="row m-0">
      <div class="col-12 col-lg-6 pl-0 post-photo-container">
        <%= image_tag @post.photo, class: 'img-fluid' %>
      </div>

      <div class="col-12 col-lg-6 px-2">
        <div class="row m-0">
          <div class="col-6 text-left pl-0">
            <strong><%= @post.caption %></strong>
          </div>
          <div class="col-6 text-right pr-0">
            Uploaded by:
            <div class="mt-0">
              <div class="d-block mb-1">
                <% if @post.user.avatar.present? %>
                  <%= image_tag @post.user.avatar_url(:small_thumb), class: 'tiny-thumb' %>
                <% else %>
                  <%= image_tag 'default_avatar_small.png', class: 'tiny-thumb' %>
                <% end %>
                <strong>
                  <%= @post.user.firstname %> <%= @post.user.lastname[0] %>.
                </strong>
              </div>
              <% if current_user && current_user == @post.user %>
                <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-outline-green btn-sm' %>
                <%= link_to 'Delete', @post, class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="text-left mt-4">
          <% @post.comments.each do |comment| %>
            <div class="mt-1">
              <% if comment.user.avatar.present? %>
                <%= image_tag comment.user.avatar_url(:small_thumb), class: 'tiny-thumb' %>
              <% else %>
                <%= image_tag 'default_avatar_small.png', class: 'tiny-thumb' %>
              <% end %>

              <strong><%= comment.user.firstname %> <%= comment.user.lastname[0] %>. <i class="fas fa-long-arrow-alt-right"></i></strong>

              <%= comment.message %>
            </div>
          <% end %>

          <%= simple_form_for @comment, url: post_comments_path(@post) do |f| %>
            <%= f.input :message, 
                        label: false,
                        autofocus: true,
                        maxlength: 240,
                        hint: ("Maximum: 240 characters"),
                        id: "comment-input",
                        input_html: { class: 'mt-3'} %>
            <%= f.submit 'Add comment', class: 'btn btn-green btn-300 mb-2' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-2 col-sm-1 p-0 order-3 order-sm-3 mt-3">
    <% if !@older_post.nil? %>
      <%= link_to post_path(@older_post) do %>
        <i class="fas fa-arrow-right fa-2x d-block"></i>
        <small>Older</small>
      <% end %>
    <% end %>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="mt-3 mt-sm-0 py-0 py-sm-5">
  <% @posts.each do |post| %>
    <div class="thumb-container thumb-container-size">
      <%= link_to new_user_session_path do %>
        <%= image_tag post.photo_url(:blurred), class: 'thumbnail mr-4' if post.photo.present? %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/change_avatar.html.erb
<div class="form-reg py-5">
  <h2 class="mb-4">Change avatar</h2>

  <div class="mb-3">
    <% if @user.avatar.present? %>
      <%= image_tag @user.avatar_url(:thumb), class: 'avatar' %>
    <% else %>
      <%= image_tag 'default_avatar.jpg', class: 'avatar' %>
    <% end %>
  </div>

  <%= simple_form_for @user do |f| %>
    <%= f.input :avatar, label: false %>
    <%= f.submit 'Update', class: 'btn btn-green btn-300 mt-3 mb-2' %>
  <% end %>


  <%= link_to 'Cancel', user_path, class: 'btn btn-outline-blue btn-300' %>
</div>

app/views/users/edit.html.erb
<div class="form-reg py-5">
  <h2 class="mb-4">Edit user info</h2>

    <%= simple_form_for @user do |f| %>
    <div class="text-left">
      <%= f.input :firstname,
                  label: 'First name' %>
      <%= f.input :lastname,
                  label: 'Last name' %>
      <%= f.input :email,
                  label: 'E-mail' %>
    </div>
      <%= f.button :submit, 'Update', class: 'btn btn-green btn-300 mt-4 mb-2' %>
    <% end %>

  <%= link_to 'Cancel', user_path, class: 'btn btn-outline-blue btn-300' %>
</div>

app/views/users/show.html.erb
<div class="container py-5">
  <h2 class="mb-4">Profile</h2>

  <div class="row mb-5">
    <div class="col-12 offset-0 col-lg-5 offset-lg-1 col-xl-4 offset-xl-2 mb-4">
      <div>
        <% if @user.avatar.present? %>
          <%= image_tag @user.avatar_url(:thumb), class: 'avatar img-fluid' %>
        <% else %>
          <%= image_tag 'default_avatar.jpg', class: 'avatar img-fluid' %>
        <% end %>
      </div>
      <%= link_to 'Change avatar', change_avatar_path(current_user.id), class: 'btn btn-outline-green btn-sm mt-2' %>
    </div>

    <div class="col-12 col-lg-5 col-xl-4 user-info">
      <div class="mb-3">
        Name: <strong><%= @user.firstname %> <%= @user.lastname %></strong>
      </div>
      <div class="mb-3">
        E-mail: <strong><%= @user.email %></strong>
      </div>
        <%= link_to 'Edit user info', edit_user_path(current_user.id), class: 'btn btn-outline-green btn-sm mr-2 mb-1' %>
        <%= link_to 'Change password', edit_user_registration_path(current_user.id), class: 'btn btn-outline-green btn-sm mb-1' %>
    </div>
  </div>

  <h4 class="mb-4">Your uploaded photos:</h4>

  <% if @user.posts.empty? %>
    <p>
      You have not uploaded any photos yet. Click
      <strong><%= link_to 'Upload', new_post_path %></strong> to go to the Upload page.
    </p>
  <% else %>
    <% @user.posts.each do |post| %>
      <div class="thumb-container">
        <%= link_to post_path(post) do %>
          <%= image_tag post.photo_url(:thumb), class: 'thumbnail mr-4' if post.photo.present? %>
        <% end %> 
      </div>
    <% end %>
  <% end %>
</div>